version: 2
jobs:
  test:
    environment:
      FASTLANE_SKIP_UPDATE_CHECK: 1
    macos:
      xcode: "9.2.0"
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      # Ruby dependencies
      - run:
          name: Set Ruby Version
          command: |
            echo "ruby-2.4" > ~/.ruby-version
            chruby
      - restore_cache:
          key: 2-gems-{{ checksum "./PRODUCTNAME/Gemfile.lock" }}
      - run:
          name: Restore Gems
          command: |
           export BUNDLE_GEMFILE=./PRODUCTNAME/Gemfile
           bundle check || bundle install --path vendor/bundle
      # Download CocoaPods specs via HTTPS (faster than Git)
      # and install CocoaPods.
      - run:
          name: Install CocoaPods
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      # Python dependencies
      - restore_cache:
          key: v3-python-requirements-{{ checksum "requirements.txt" }}
      - run:
          name: Install Python dependencies
          command: pip install -r requirements.txt
      - save_cache:
          key: v3-python-requirements-{{ checksum "requirements.txt" }}
          paths:
            - "~/Library/Caches/pip"
            - "/usr/local/lib/python2.7/site-packages"
            - "/usr/local/lib/site-python"
            - "/usr/local/bin/cookiecutter"
      # - run:
      #     name: Install Cookiecutter
      #     command: pip install cookiecutter
      # Restore CocoaPods
      # - restore_cache:
      #     key: 2-pods-{{ checksum "./PRODUCTNAME/app/Podfile.lock" }}
      # Run tests
      - run:
          name: Test Cookiecutter Template
          command: |
            echo Testing branch ${CIRCLE_BRANCH}
            cookiecutter --no-input https://github.com/raizlabs/ios-template.git --checkout ${CIRCLE_BRANCH}
            cd ProjectName/app
            bundle install
            bundle exec fastlane test
      - run:
          name: Fastlane
          command: |
            cd PRODUCTNAME/app
            bundle install
            bundle exec fastlane test
      # Cache CocoaPods
      # - save_cache:
      #     key: 2-pods-{{ checksum "./PRODUCTNAME/app/Podfile.lock" }}
      #     paths:
      #       - "~/.cocoapods"
      - save_cache:
          key: 2-gems-{{ checksum "./PRODUCTNAME/Gemfile.lock" }}
          paths:
            - vendor/bundle


workflows:
  version: 2
  test:
    jobs:
      - test
