version: 2
jobs:
  test:
    environment:
      FASTLANE_SKIP_UPDATE_CHECK: 1
    macos:
      xcode: "9.2.0"
    shell: /bin/bash --login -o pipefail
    override:
      - 
    steps:
      - checkout
      - run:
          name: cookiecutter
          command: |
            pip install cookiecutter
            cookiecutter --no-input https://github.com/raizlabs/ios-template.git --checkout ${CIRCLE_BRANCH} 
      - run:
          name: Fastlane
          command:  |
            cd PRODUCTNAME/app
            bundle install
            bundle exec fastlane test

dependencies:
  pre:
    - "[[ ! -s \"$(git rev-parse --git-dir)/shallow\" ]] || git fetch --unshallow"
    - xcrun instruments -s #list available devices
    - xcrun instruments -w 'E8DD285C-51EE-4DB5-B326-7E927686EC36' || true #mitigate scenario where simulator resource isn't available - device is iPhone 6s (9.3)

workflows:
  version: 2
  build-test-adhoc:
    jobs:
      - test
