version: 2
jobs:
  test:
    environment:
      FASTLANE_SKIP_UPDATE_CHECK: 1
    macos:
      xcode: "9.2.0"
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      # Ruby dependencies
      - run:
          name: Set Ruby Version
          command: |
            echo "ruby-2.4" > ~/.ruby-version
            chruby
      - restore_cache:
          key: 1-gems-{{ checksum "./PRODUCTNAME/Gemfile.lock" }}
      - run:
          name: Restore Gems
          command: |
           export BUNDLE_GEMFILE=./PRODUCTNAME/Gemfile
           bundle check || bundle install --path vendor/bundle
      - save_cache:
          key: 1-gems-{{ checksum "./PRODUCTNAME/Gemfile.lock" }}
          paths:
            - vendor/bundle
      # Python dependencies
      # - run:
      #     name: Pre-install Python CLI packages
      #     # This is required since when we cache the output of pip, it doesn't also cache
      #     # /usr/local/bin, where the CLI gets installed
      #     command: pip install $(grep -i -e coverage -e fabric -e aws requirements.txt)
      - restore_cache:
          key: v1-python-requirements-{{ checksum "requirements.txt" }}
      - run:
          name: Install Python dependencies
          command: pip install -r requirements.txt
      - save_cache:
          key: v1-python-requirements-{{ checksum "requirements.txt" }}
          paths:
            - "~/.cache/pip"
            - "/usr/local/lib/python2.7/site-packages"
            - "/usr/local/lib/site-python"
      # - run:
      #     name: Install Cookiecutter
      #     command: pip install cookiecutter
      # Run tests
      - run:
          name: Test Cookiecutter Template
          command: |
            echo Testing branch ${CIRCLE_BRANCH}
            cookiecutter --no-input https://github.com/raizlabs/ios-template.git --checkout ${CIRCLE_BRANCH} 
      - run:
          name: Fastlane
          command: |
            cd PRODUCTNAME/app
            bundle install
            bundle exec fastlane test

workflows:
  version: 2
  test:
    jobs:
      - test
