version: 2
jobs:
  test:
    environment:
      FASTLANE_SKIP_UPDATE_CHECK: 1
    macos:
      xcode: "9.3.0"
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      # Ruby dependencies
      - run:
          name: Set Ruby Version
          command: |
            echo "ruby-2.5" > ~/.ruby-version
            chruby
      - restore_cache:
          key: 2-gems-{{ checksum "./PRODUCTNAME/Gemfile.lock" }}
      - run:
          name: Restore Gems
          command: |
           export BUNDLE_GEMFILE=./PRODUCTNAME/Gemfile
           bundle check || bundle install --path vendor/bundle
           unset BUNDLE_GEMFILE
      # Download CocoaPods specs via HTTPS (faster than Git)
      - run:
          name: Install CocoaPods
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      # Python dependencies
      - restore_cache:
          key: v3-python-requirements-{{ checksum "requirements.txt" }}
      - run:
          name: Install Python dependencies
          command: pip install -r requirements.txt
      - save_cache:
          key: v3-python-requirements-{{ checksum "requirements.txt" }}
          paths:
            - "~/Library/Caches/pip"
            - "/usr/local/lib/python2.7/site-packages"
            - "/usr/local/lib/site-python"
            - "/usr/local/bin/cookiecutter"
      # Run tests
      - run:
          name: Test Template Itself
          command: |
            cd PRODUCTNAME/app
            bundle install
            bundle exec fastlane test
      - run:
          name: Test Template Output
          command: |
            echo Testing branch ${CIRCLE_BRANCH}
            cookiecutter --no-input https://github.com/raizlabs/ios-template.git --checkout ${CIRCLE_BRANCH}
            cp -r PRODUCTNAME/app/Pods ProjectName/app/Pods
            cd ProjectName/app
            bundle install
            bundle exec fastlane test
      # Cache Gems
      - save_cache:
          key: 2-gems-{{ checksum "./PRODUCTNAME/Gemfile.lock" }}
          paths:
            - vendor/bundle

workflows:
  version: 2
  test:
    jobs:
      - test
